#!/usr/bin/env python
# -*- coding: utf-8 -*- 

import argparse
from robobo.robobo_arucos import ROBOBO_ARUCOS

def start_robobo_arucos():
    dictTypes = ["DICT_4X4_50",
                "DICT_4X4_100",
                "DICT_4X4_250",
                "DICT_4X4_1000",
                "DICT_5X5_50",
                "DICT_5X5_100",
                "DICT_5X5_250",
                "DICT_5X5_1000",
                "DICT_6X6_50",
                "DICT_6X6_100",
                "DICT_6X6_250",
                "DICT_6X6_1000",
                "DICT_7X7_50",
                "DICT_7X7_100",
                "DICT_7X7_250",
                "DICT_7X7_1000",
                "DICT_ARUCO_ORIGINAL",
                "DICT_APRILTAG_16h5",
                "DICT_APRILTAG_25h9",
                "DICT_APRILTAG_36h10",
                "DICT_APRILTAG_36h11"]

    parser = argparse.ArgumentParser(description="This script starts the Robobo ArUco system")
    parser.add_argument("-n", "--robobo_name", help="The name of the robot")

    """TODO: Parse and pass optional arguments correctly without having to if-chain"""
    #parser.add_argument('-p', "--calibration_path", help="The path to the calibration image")
    #parser.add_argument('-d', "--dictionary", choices=dictTypes, help="The type of ArUco dictionary to use")

    """Create a Robobo ArUco Detection object and run it"""
    args, _ = parser.parse_known_args()
    kwargs = vars(args)
    robobo_name = kwargs.pop("robobo_name", None)
    arucos_system = ROBOBO_ARUCOS(robobo_name)

    arucos_system.run()
if __name__ == "__main__":
    start_robobo_arucos()
